repos:
  - repo: local
    hooks:
      - id: check-file-names
        name: Check File Names
        language: python
        entry: python -m scripts.check-file-names
        args: [
          "accounts_v2.0.1", "accounts_v2.1.0","automatic-payments_v1.0.0",
          "bank-fixed-incomes_v1.0.0", "bank-fixed-incomes_v1.0.1","bank-fixed-incomes_v1.0.2",
          "business_v2.0.1","consents_v2.0.1", "consents_v2.1.0", "consents_v2.2.0",
          "consents_v3.0.0","credit-card_v2.0.1","credit-card_v2.1.0",
          "credit-fixed-incomes_v1.0.0","credit-fixed-incomes_v1.0.1",
          "exchanges_v1.0.0","enrollments_v1.3.0","financings_v2.0.1","financings_v2.1.0",
          "funds_v1.0.0","funds_v1.0.2","invoice-financings_v2.0.1", 
          "invoice-financings_v2.1.0", "loans_v2.0.1", "loans_v2.1.0",
          "payments_v2.0.0","payments_v2.0.1","payments_v3.0.0",
          "payments_v4.0.0", "personal_v2.0.1","resources_v2.0.1", 
          "resources_v2.1.0",  "resources_v3.0.0","treasure-titles_v1.0.0",
          "treasure-titles_v1.0.1","unarranged-overdraft_v2.0.1","unarranged-overdraft_v2.1.0",
          "variable-incomes_v1.0.0","variable-incomes_v1.0.2"
        ]
        exclude: ".*"
        always_run: true
      - id: check-json-files
        name: Check Json Files
        language: python
        entry: python -m scripts.check-json-files
        args: [
          "accounts/2.0.1/", "accounts/2.1.0/","automatic-payments/1.0.0",
          "bank-fixed-incomes/1.0.0/", "bank-fixed-incomes/1.0.1/","bank-fixed-incomes/1.0.2/",
          "business/2.0.1/","consents/2.0.1/", "consents/2.1.0/","consents/2.2.0/" 
          "consents/3.0.0/","credit-card/2.0.1/","credit-card/2.1.0/",
          "credit-fixed-incomes/1.0.0/", "credit-fixed-incomes/1.0.1/",
          "enchanges/1.0.0/","enrollments/1.3.0/","financings/2.0.1/","financings/2.1.0/",
          "funds/1.0.0/","funds/1.0.2/","invoice-financings/2.0.1/"
          "invoice-financings/2.1.0/", "loans/2.0.1/", "loans/2.1.0/",
          "payments/2.0.0/", "payments/2.0.1/", "payments/3.0.0/", 
          "payments/4.0.0/","personal/2.0.1/", "resources/2.0.1/",
          "resources/2.1.0/",  "resources/3.0.0/","treasure-titles/1.0.0/",
          "treasure-titles/1.0.1/","unarranged-overdraft/2.0.1/","unarranged-overdraft/2.1.0/", 
          "variable-incomes/1.0.0","variable-incomes/1.0.2"
        ]
        exclude: ".*"
        always_run: true
